# Generated by Django 4.2 on 2024-11-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(null=True, unique=True, verbose_name='ID of user')),
                ('user_login', models.CharField(max_length=255, unique=True, verbose_name='Login')),
                ('user_password', models.CharField(max_length=128, verbose_name='Password')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Registered')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered time')),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
                'db_table': 'telegram_users',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subcategory Name')),
                ('description', models.TextField(blank=True, verbose_name='Subcategory Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Subcategory Creation Time')),
                ('subcategory_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bot_file.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'db_table': 'subcategories',
                'ordering': ['-created_at'],
            },
        ),
    ]
