# Generated by Django 4.2 on 2024-11-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Images')),
                ('name', models.CharField(max_length=100, verbose_name='Names')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Edited date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(null=True, unique=True, verbose_name='ID of user')),
                ('user_login', models.CharField(max_length=255, unique=True, verbose_name='Login')),
                ('user_password', models.CharField(max_length=128, verbose_name='Password')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Registered')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered time')),
                ('admin', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bought_products', models.ManyToManyField(to='bot_file.product')),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
                'db_table': 'telegram_users',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('promo_name', models.CharField(max_length=100)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('who_have', models.ManyToManyField(related_name='promocodes', to='bot_file.telegramuser')),
            ],
        ),
    ]
