# Generated by Django 4.2 on 2024-11-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='bought_products',
            field=models.ManyToManyField(blank=True, to='bot_file.product'),
        ),
    ]
