# Generated by Django 4.2 on 2024-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_file', '0002_alter_telegramuser_bought_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
