# Generated by Django 4.2 on 2024-12-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_file', '0003_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='balance',
        ),
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.IntegerField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Promocode',
        ),
    ]
